### ISSUE TITLE
issue when trying to download

### ISSUE THREAD

**Issue by crimegremlin** [Tel0k/Aurora-Builder-Valdas-Spire-of-Secrets#1]
when I try to have aurora download this from the URL it says that on line 16, position 76 there is an unexpected token, with the aurora expecting a = instead of a >

**Comment by Tel0k** [comment]
You probably are using the wrong url.. When adding indexes to Aurora you
have to use the raw url not the GitHub page one..
https://raw.githubusercontent.com/Tel0k/Aurora-Builder-Valdas-Spire-of-Secrets/main/elements/valdas-spire-of-secrets.index
This is the correct one you must use.

Il mer 22 giu 2022, 03:58 crimegremlin ***@***.***> ha
scritto:
