### ISSUE TITLE
Alchemist multiclassing

### ISSUE THREAD

**Issue by FreshRoyal** [Tel0k/Aurora-Builder-Valdas-Spire-of-Secrets#2]
The alchemist has stats for multiclassing, even though it cannot multiclass (at least in the initial release of the book). If they're supposed to be there, then the ability scores required seem wrong. It's current Strength/Dexterity plus Charisma

**Comment by Tel0k** [comment]
you are right, multiclassing ability score requirements are wrong.. it was Intelligence 13, and it seems like it had always been that way
